### ISSUE TITLE
Create a mockup

### ISSUE THREAD

**Issue by khanshakeeb** [khanshakeeb/wad_fall_18_bs#1]
Create a mockup by referring two sites olx and gumtree

**Comment by hmkhambaty** [comment]
[Untitled Diagram (1).pdf](https://github.com/khanshakeeb/wad_fall_18_bs/files/2543866/Untitled.Diagram.1.pdf)
group members:
huzaifa nasir
mohsin ghani
mohammad soban
mohammad aftab
faran-ul-haq

**Comment by hmkhambaty** [comment]
https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram%20(1).xml#R%3Cmxfile%3E%3Cdiagram%20id%3D%226add7c2d-1205-4bbb-a78c-86e0cff6aea1%22%20name%3D%22login%22%3E7Vhbj9soGP0t%2B5DHWAZiJ3lsMpeutJUqpdI%2BE4xtNNi4GI8z%2B%2BsXbHzF086omZmVukSK7APmg3OO4TMrdMwu9xIX6RcRUb6CfnRZoZsVhNtdqP8N8NQCaLdtgUSyqIXAAJzYP9SCvkUrFtFy0lAJwRUrpiAReU6JmmBYSlFPm8WCT6MWOKEOcCKYu%2BjfLFJpi%2B4Cf8A%2FU5akXWTg25ozJg%2BJFFVu460gipvSVme468u2L1MciXoEodsVOkohVHuVXY6UG2o72trn7p6p7cctaa5e8gBsH3jEvLJTr0oqc5xROz711HGi6EV3eUhVxjUA9GWppHigR8GF1Eguct3yEDPOZxDmLMn1LdGDoho%2FPFKpmGb7k63IWBSZMIc6ZYqeCkxMzFpbS2MNm9SM1zfdi1yd7KAWZmshE4BeRpCd%2FT0VGVXySTextbBTzjoVhPa%2BHnTfWCgdSd4JiK3Tkr7ngW19YQlfJj9wyC9wWdZCRr8r%2Bfv3Iz90yP9mOP5vEn8NrvcfZ%2FTt7871O%2Fp673AdC5no%2FcTMya4u6M7hvmW62%2BzATIZulzL8RLhMe7J0TWF6yC6JSQQ8JkqPGXH%2FzItKOQrq7XDTFLuYjHC%2FKRo%2FV0qJvDGIrrCLTpsh7GbqD7vrsrCdLTiN1XWURXCqLNy5yu4XlAXBrysLkCPtCobczAybcJLGDRp%2Br0z6oIVSeIU%2BNbkOvNO9wCPxN6EfErzG1I%2FWeB%2BQ9W4P9F8Ux5Cct4Ts8dCBvkoaDTWLVdHF0n3hruZNbXRojPAaD%2FVmeJ2HoqaMcdhWoJsgCIOfmKtfc65hr9nC0a8S44UDecEbGWzzywYLYYg3KN5ob5FgTREE6zM447W%2Fi3wASLgFYO8ajIuE5f%2F76x381SX8H%2BMvN%2BHtRE%2BDTvK6rj3C9U7FYhp5RGRe8TCyxtDQ8YaTN4xt8ipvbCvmVZK7SlLf%2FJYsQ3zzW7DGqKVVHTbFddcEH7mp1L5gefJNaFfcwDdyBphtbMg1RhAubGzoCikLcHPxE8WSpJ7n%2FVDlF2t61h%2FUWghceFI25wXPphHSEh8sidy%2FyLPEwir0V3N3g6YSAt%2BVuu9o6cW%2FgprBbpaA%2Bq6c%2FcfXtTNQ4Kb79%2BKPqwtpBt0v4S%2BTbeHLYS7U4vcBLXWL%2FsAHLGsUvlYk4EiCfqCIpBwr9jg9oFqSycb7KliuhmDr%2BYsq4rikytG1H%2BaS1Pp2OJpqmw%2FHf%2Bj2Xw%3D%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%22c04606ca-ae0d-a95c-891c-8dff2cb7cc9a%22%20name%3D%22signup%22%3E7Vpbb5swFP4te%2BBxiEvI5XFNu25Sd5EyadujAw54BYyMKcl%2B%2FY7BXE3aTKVMFUukCh8fH%2BPvO%2BfYzqlmb6PjLUNJ8Il6ONQswztq9rVmWav1Ev4KwakULAy7FPiMeKXIbAQ78htLoSGlGfFw2lHklIacJF2hS%2BMYu7wjQ4zRvKt2oGF31gT5WBHsXBSq0u%2FE40EpXTtGI%2F%2BAiR9UM5uG7Nkj995nNIvlfJplH4pP2R2hypbUTwPk0bwlsm80e8so5eVTdNziUEBbwVaOe3%2Bmt35vhmN%2ByYBFOeABhRmu3ngZwtCrwIEnXzzlea67IUpTcsCe7tJIT%2B4rLbDcKMol8VMFY8CjEJ5M6Es5o%2Fc1mIWkWroBDQ%2BlAfZkA3oSYSE6%2BsK7dELTVUb0jIGxqwMJwy0NKSumsLEhvvUErR7XEF%2Fo2Wec0%2FgbPhaIdDStUtUqPsI4jXnLREcuvXQtLCTIJbH%2FjSYgEP0oJH4Mzy7AjlkNxQNmHB%2FPUmPWhEMcYRphzk6gUg2ofETGkC2beeOQzlLKgpYzVnpIxoBfW278AB6kKwy7haO4RQoLzBIYx7BPUrHIPtm8ALjHQ0xj3CNNilq%2B0UIXHFK2pWHRL2AkEJzvJMoR8TzRqcLe8akROFh3KdioFNSR36ZgMQIFS4WCGEX4HOpKpD1NgALeWZjzgHC8A58Xc%2BYQkiArclw7YkfFve%2F75lJFfjEAvDUC8CsF%2BOsvamqbCe4DHv9SuFd7f2cv6qGOPdimZZMyHlCfxii8aaQ9fFr0%2FMKcn2SWQRmnIGos3NEilZs1imKixzGE96IZc6XWWh5SEPOx1NoMI81wiDh56Fp%2FDm5rBbbt54%2FbmTps7YlTOKy6S74eh92oDmsuJvLYjYJbAqfLnDJvrl474fZmqkd%2BhvkJDtxiBbOioXe6GzzemS9Fgz1mrsBHwn8Ise7I1s9JsshSzSLLiZKIqWaR15N96x812ul3PRVy6tWiuBzPI%2Bjtf3i1MNWz2oyRn3LXs9TLxYyRn%2FJaV73tf%2BSnvp9UG%2BKr3CHNgaPFOawv3iHl0K%2BUwMwNR4tedKx74JfvJUc1%2BD9pqE5wlaFyMYqhgsh6PZdxq57i5xxVU%2Bazgd%2FGs31E5oL9wnA62NurCbFXz087jJgb6LquwN%2FG%2FeJS055SDiyhRGesKCz2602ymgcoy9TnKLyClld8WkyG%2BFAUR8rC0V3Rura1Tu3DNDSlAlUbGiJ6BDad3h24Lme02LSGShyj0Kle4W7pm9GJFC99VdQAL6ZtICb7RA1GHk5Bo64Mm5dyZJ25%2BnVHtCixH2Hkmbvh2379kB4OKf7L%2FUrUCesadqne%2FJ%2BAffMH%3C%2Fdiagram%3E%3Cdiagram%20id%3D%22626a43f4-a9c5-e321-b1ba-08d011c67119%22%20name%3D%22dashboard%22%3E7Vldj6M2FP0tfcgjkY3BkMcm3dk%2BtFKlWanPxjYBBTB1nEnSX18D5ptk0YZEO1IZaWSu7Wvjc871tbNCu%2FTyVZI8%2BlMwnqxswC4r9NvKtj0f6%2F%2BF4VoZHIAqw17GrDLB1vAe%2F8uNERjrKWb82GuohEhUnPeNVGQZp6pnI1KKc79ZKJL%2BqDnZ85HhnZJkbP07ZiqqrL4LWvvvPN5H9cgQmJqA0MNeilNmxlvZKCyfqjoltS%2FT%2FhgRJs4dE%2FqyQjsphKpK6WXHk2Jp62Wr%2Br3dqG3mLXmm5nSwqw4fJDnxesY40V23katL%2B6J0Pp%2FXNCHHYxxytqYiXeeHupX23DY0n6Su9TJGKk10Ceq6o5Li0Cxmaak%2FHegXRo4RZ%2BZF1%2BSFh%2FSyL9i1jsXRO8Xrk9TOtmGcJDuRCFkOgTgo%2FpoBOjUUFH%2B6JjgpJbJv%2FFKuSK%2BlXTW1y6dwLjLVcdGzG5b6hYec0DjbfxO5NhT1JIn3mS5TvexcNkvxwaXil5vQwAZwrSMuUq7kVTepO9QcMRpC5vXcEtLFxhZ1yFi3I0YD%2B8ZzywNdMFSYpoUzQYunYitlKeOtNKuMphAFwAdvYMwBozC01S5ZzFsIM5Hx54DhvxAM96ZGSTGa5GFpxf%2Bciqihl1uRFfq1DHH2m3Zi7zCEFHuBa%2Fkuxha1KbAwc30LBMhFPEBhQILWQS3nVASxRrtVOrkp9D5UcRZxGasBUK11CFNbsyypEh6qbSn%2BAbMGcp7FD2eaHx0CQOdJBMAPE8BBAMEN5pYfBp6lyYwtHxJihYw5yA9dHgZ4TIAgPuhN%2BPPiPwwqYFnoTYepWPA0KngPU4EzanPsuRaikFmc%2BsDioQ4IDsUcupAxWMxzSAX1UeB%2FYnplPzMhCjCeHRFMB8d%2BIS38h2kBfcY2JGDWhgfQckMdIWiAqcU8vsE00LzY%2BGNaUCLn8eH5wp6dLbT2frLXZBHLc6HB%2FRVc2DzMBd%2BnHkNMbw8Op5bLkG%2FZNAwtGLi%2BDzdIH3Im0oUfdzQjnBgeEKoKuLbnKFb8XWfhhfGsqTEIFV1CLZD9ebif%2FTnuCM4pNPECaNYn4g6c75xIGq3X67sqm62pQB82tXhI3sjqVnpdy82dkhsrn85ZqMi%2B2rPSH%2BXbMNbCCR02jqZAXgBMDPpgwolAbYMJOO0l4IQjOL%2BKXxYHcnKfuw9bF3RzbhoCNQWI5EfdorkMgbMxAndBgiNI0B1EJE%2BIij%2F6lzdTMJnx%2FhKxnkczmDUMuyIMj1yNcG2mOQ%2FqqbuVyTRp3l44umPok6RHhVTQwykf7ZPw3uF5RA1cPg%2BK7nbE9Kb2v0U0hkYLb7Rgg1sQPJ6pvhjKwVkGeuNA2uBXtjNfDBvNdqc6D2F7GuLvYOo%2BKNJr382yGh1fdDVUQf9T5ZNSpbmNX5Yr43u4hivOZ%2BVKIPQXpKNUAf5EnLn2eryGQdZzos34Iq9hEHx1bqBE%2FkOw94%2FJHdjHx2w6nVc0NT95cLmRb%2BjX9ve5igXtb6Doy38%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%221613ea4b-f0a3-f325-c8ce-5f3a71fe7952%22%20name%3D%22addproduct%22%3ErVRNb6MwEP01XBHBCck5aXf30lMq9eyaCbZiGGRMIfvrdww2H00qtdIaCY3ffOE3z0TsVPa%2FDa%2FlC%2BagozTJ%2B4g9RWm6P2T0dsBtBLYJG4HCqHyENjNwVn%2FBg4lHW5VDswq0iNqqeg0KrCoQdoVxY7Bbh11Qr7vWvIA74Cy4vkffVG7liB52yYz%2FAVXI0HmTeM87F9fCYFv5flHKLsMa3SUPtXx8I3mO3QJizxE7GUQ7WmV%2FAu2oDbSNeb%2B%2B8E7fbaCy30lIx4QPrlsIX5xpSj3KHVmFs7qui4XmTaMukMcCy7i%2BhiiqPAf6I9lboFHaUpO1IV9jDV4nMgckHD2hTc4bCbnfkKd2Fcq%2BcOqKFTb7VsWtoWLHi9L6hBrN0IJB4p6pwcIjEveQ5721FqtX6AdGVpHpGJoOyxXHyi5KrHCv0oOrUHOhquIVawKcn2tVVGQLoh3MRMUHGAv9l6PZTAOnewRYgjU3CgkJQSP%2BDjG%2F7WZB7jKPyYUYQxz3d6CYKs86IMNL4bEs2ANZfJptGBIX1tF17KSycCZiHNjR3JyGFvNfTvs%2FsLPP1uxsd3fsbB%2BQk%2F2cHNrO93HwLf557Pkf%3C%2Fdiagram%3E%3Cdiagram%20id%3D%2288c7d3da-f4ec-5d38-2cff-1b588193bacb%22%20name%3D%22profile%22%3E5Vpdj6M2FP0tfeBxEeBAyGOTmf2Qpu1Is1LbRwcccMdgZMyQ9NfXBvNp72y2YjMjQaQIXxvbnHN8ry9ggUN2%2FsRgkf5GY0Qsz4nPFrizPG8bBuJfGi6tYeOA1pAwHLcmdzA84X%2BRMjrKWuEYlZOGnFLCcTE1RjTPUcQnNsgYrafNTpRMRy1ggjTDUwSJbv0TxzxtraHvDPbPCCdpN7LrqJojjJ4TRqtcjWd54NQcbXUGu75U%2BzKFMa1HJnBvgQOjlLdn2fmAiIS2g6297uM3avt5M5Tzay7w2gteIKlQN%2BOAiEv3qS%2FOEnlW17UdEViW%2BIRiO6KZXTx3rUTPQ0N1S%2FzSwZjyjIgzV9SVnNHnHszG0t26IwoxLFMUq4KoKWQP2TmR6rIxLbcVtismOtufMCEHSihrhgDIkb9%2BgFFN5MifqDlWnNP8Kzo3iExaem1Trzlk5zTnoy4mdqXSUPZQwAjnyVdaCIOshwQnuTiPBOyI9VC8IMbR%2BZvUuD3hYh0hmiHOLqJJd0GnEbWGgCrWgyD9QNnSkRi7dlCtgaTvedCBOFFSMMsCGGQx47YjCUZcwrWvU8zRkwBGGmvBm9TQiP8x2wugsw2m6Gx8DZ2NAZxgAXA2GjhPCLIotW371RVwtd6PYvkLkcLCZqzxbnPRK5cC9kyJ0jctgLg5Ruok6MQH9T40pTswlbfr6Mug78jE8QJcBs6Uy175IzI9x8CmtwCbvsbmJ%2FrL4jzKOe8bP3Q1a2POc5ojA08mPhgqRYs%2BOrnXUrR53RlphIBX%2BGCIQI5fpsHURJIa75FiMY1%2BsA9zF0ZPpxJxjdV%2BmlcRHWhE5zBDGtO8iRN7LXTNqdDZ0YKARByLTcWvqiLDcSyHMfMmNw1jKS3qLufBxA30JWbyl0ussK0G%2FN0f%2Bl5hJbjvbod7%2BP0gjmKx7VVFynhKE5pDcj9YZ%2FCM2PkHcX5RzghWnArT0MMDbbZGg%2FORA00gLGnFImXatSYOWYL6HfXVSF%2FtbK7Fbafhdvj9y2GlgvUMsfhnCbbL%2Ft6%2FYjt5TiTrvZ1ku%2FmMkCtEwlZTFq9VtzcMcB3zI%2FQZ4hexF5R3sCoawhkLhnDnuj%2BLBrCkt0BnzP%2BSZttXpb%2BX9yOB7kaCN%2FQiemb7Xv1vaPC%2Fb4mcnkU2z5vWsejBGyYXrp7WrRj5m0Y9Pa9bMfK3TOxcPbNbMfI3zVD03PC9RkjfECHD5SOk%2BQke2MxWRzgDv52qumrA%2F7sdaQ%2Fw2%2FvTOvofzwc9Pftc86q6oT%2Fz9Oy1rI4ZXgv2G8efYA%2B2N8Rez10fGRUA6k%2FGfwR1ywOOs93dBcJO4BGRR1pijqmRgodZg56KOUdcekCdyvFrEfk2llac4FxMr%2Fs4oCFt%2FM72Q2Bpb7k%2BNoelv8YR80IZLOxC4bK8AHbTtRfq7zL7xxtj%2Frc%2Fzr8oDh8XtE5y%2BIAD3P8H%3C%2Fdiagram%3E%3Cdiagram%20id%3D%22611c67b5-8566-c2c0-6d58-0b353eb3fbab%22%20name%3D%22mobile%22%3ErVbBbqMwEP2WPeS4yECguW5It3voSpVSac8OGLBiGGRMSffrdwzGQKBtVoojRfbzeGzmvRl740fF5UnSKv8NCRMbjySXjX%2FYeN7DLsR%2FDbz3wJb4PZBJnvSQOwJH%2FpcZkBi04QmrZ4YKQChezcEYypLFaoZRKaGdm6Ug5rtWNGML4BhTsUT%2F8ETlPboLyIj%2FYjzLh51dYmZOND5nEprS7Lfx%2FLRr%2FXRBB1%2FGvs5pAu0E8h83fiQBVN8rLhETOrRD2Pp1Pz%2BYteeWrFS3LPD6BW9UNGw4cShw6T4PsJfpXtu2TixoXfOUJU4MhVOdByv0PBqaT1LvQxhzVQjsuThXKwlnG8wOGT6d4CChdc4SM8CZSnsoLplWl8Ohfmi400h0tk%2B5EBEIkN0WPiP6ZzeYzMRE%2F3Dm1CgF5Su7dBGZWXq9qdc17RxKNXExw41Kd9pDRWNeZq9QIaDnqeBZif0Yw86kDcUbk4pdPqTGtYRjHjEomJLvaDIsGDRicsg3w3YUZBAaLJ%2BIcbCjJgcy63nUAXaMFNZl4a%2FI4orbgSQaKx2ufZtzxY4YGA22yJvW0IT%2FKdt3iM5DOI%2FONlhEZ7sSnPAOwdkugnNkVMa54zifZsDNej9h%2BqNIaeVI2VW3a9GbkuLvpRFlsJYASdcm6hQsVaN6n7vRwZ%2FL2yXLNLCO1ji%2BA5chmXNplT8h0yMrbHp3YDNYsPkE3%2B7Ooz7zvqtDN7M25byEkq3wtMaHZDVa2NvJvZWi7efFaEGI%2Fwkfkgmq%2BNv8Ml0jyez3AhyPYTf7fl3CIE1rphas2mPeRHT4dU270j0hYRhFGEAdOo6vgx8mkZQu%2FBZ9picmXqDmimt6DydAngs0EFcT9nZYXBcTeUGjBC9REcPLhizzP%2BramnrC3c7d65RGBSacjZ9jFDTAB64rS3%2BsEqQm9eqK9lYEXTLVgjzXTgEnroN297LuhsG8FLgrt96K8uwD7D9KAQ7Hh1YvqPEx6z%2F%2BAw%3D%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%2218dd9abd-9eb1-5f06-cb6c-d7e96cb1dd98%22%20name%3D%22cars%22%3E3VfLjtowFP2WLlhOlAev7QADXUyrkajUtUluEmscO7LNJPTre504L5KZIpXpokGAfXxjm3POvTGzYJuVB0ny9JuIgM18NypnwW7m%2B6v1Ej8NcKmBuRvUQCJpVENeBxzpL7Cga9EzjUANArUQTNN8CIaCcwj1ACNSimIYFgs2XDUnCYyAY0jYGP1JI53W6HrhdvhXoEnarOy5duREwtdEijO36838IK6uejgjzVw2XqUkEkUPCp5mwVYKoetWVm6BGWob2ur79u%2BMtvuWwPUtN%2Fj1DW%2BEnaHZ8ZLhrZt0ga3EtIqicEJGlKIxRE4oMid%2FbaJw5i7Q%2FiR9aWhMdcaw5eGY0lK8tmRWSPPTXexERKUQ2Q6O5GaGrEyMuxwq1OpMnbPEyTYxZWwrmJDVEgG45tUu0BsJXfPCkdNZa8F%2FQFkxMoj061C%2FuszkguveFAPcunRtZshJSHnyQ%2BQImHHCaMKxHSLtIFsq3kBqKN%2BVxmsFxzwCkYGWFwxpbmg8YnMosN2iM%2BRiabG0Z8YmjtgcSNqZOx9gw1ph2hbBhC2utG1EIqE2dG2KlGo4IjEGLFA346Ge%2Fn2178DOajlkZ74YsTOfIGd5B3LmI3KOQGSYOo7zYQbc7PcTpj%2BalOSOlFV1uza9LSnBRlpTLqYSIKqunjsZxLpz73PV2wVDe3vuOA3aiaY0voOWS3eoZev8npi%2BO6Gmfwc1FyM1D%2BLL3XU0e95Udehm1fqac8FhQqcpPSQojGifTt6tEs0%2FLkYjQYIP9JDAiKZvw4fplEh2vRdBcRvtYg%2FXJUzEsQI9UrXd5k1Cr26vaTSrzgf9%2BmXYo3hAeLS5pE3tb9FncgL2IhTV1Ci8OwmUOsMAZgY27aFgKoerxR5VXp9jjKyk6cS0NOba2P3sUq3NAejR0ODvw4j7DsUjUEx5BNI8mRGNiCb4ZXDVfDPCI%2FQhV7mQSOP%2B5fsBPz1%2FXeIbW1siDxIuTs6TTyjV1w%2By1XJkpmob125qwb9J7%2FV%2FqLr3R9WZCInZlHqQgAdps3l%2FP7dSK%2B8Bqf1HYvvB6vPUxm53VK5LQvd3JHj6DQ%3D%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%22edc2e675-3c1d-ec80-efc0-4c6e151dd130%22%20name%3D%22tv%22%3EtVddb5swFP0te8jjEOBA0scl7bqHTqqUSnt2wIBVg5ExId2v3zXYgIFWdMtASuzj64%2Fcc%2B69zgYd8%2BujwGX2k8eEbXw3vm7Q%2Fcb3d%2FsQPhXw1gFbF3VAKmjcQd4AnOhvokFXozWNSWUZSs6ZpKUNRrwoSCQtDAvBG9ss4czetcQpmQGnCLM5%2BovGMuvQfeAO%2BA9C08zs7Ll65Iyj11TwutD7bXyUtE83nGOzlravMhzzZgShhw06Cs5l18qvR8KUa43bunnf3xntzy1IIddM8LsJF8xqYk4cMph6yAJoparVNI0TMVxVNCGxE%2FHcKV%2BNFaw8GOqfJN%2BMGzOZM2h5MFZJwV97Z7aI%2BekudGJcZSTWHRgp1Qr5NVXqciivdjV1agGLHRLK2JEzLtotEHHV228wGolc9cLIuZaSFy%2Fk2nrEsvQ7U7991OK8kKMlLFyrdK9WKHFEi%2FSFlwCoccxoWkA7ArcT0bviQoQk13ep8XrCIY4Iz4kUb2BiJhiN6BhCutsMggxCjWUjMRo7rGMg7VcedAANLYVlWaAFWUy4NSThSCp3HZqMSnICxyiwAd6Uhkb8j9m%2BgXd2oe2dbTDzznbBOeENnLOdOedEsIgyx3E%2BjIDVej9D%2BINIcekI0Wa3qeh1SkEHoUUZLAVA3D4jdTKSyEG9T23vHtny9tx5GPQLLXF8Ay5D1%2BayV%2F6ITN9dYNO%2FAZvBjM1H%2FuXmPKozH9o8tJq1MecFL8gCT0t8CFKBRV%2BdvLUUbT9ORjNC0Ad8CMKwpBe7mC6RpPd75hSO0W%2F2dZrCeJJURM5Y7Y%2B5iuhwVU57h9pZJZsyYwdo4KoXcIbPhD3zikrKrQKh2KBw4XiaGJw5iCQfGXzTwStVsTnwWjJawO7m3uMuVZ%2BpEMF%2FNCJOTC7wVTny8n8q1B7NK9TdXCUmVf9L1O7WFyjjhIhWEXdy%2BOwcMKLUonpCpYvC%2Fd1uKVL7LGzfbfy%2FZ%2FfWRdIzojeJNVy4Q6A5Qwb7BEPQHW6tXXQO%2FwzQwx8%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%224303196e-8fb7-1206-81aa-fdd438f5efb6%22%20name%3D%22bikes%22%3E3VdNb%2BIwEP0te%2BBIlA8IXBso3UNXqkSlPVYmmSQWThzZpqH763ecOF8kZZGW7mGDVOzniW3eezN2Z94mOz8JUqQ%2FeARs5trReeZtZ667Wvv4VwMfNbCwvRpIBI1qyOmAPf0FBrQNeqIRyEGg4pwpWgzBkOc5hGqAESF4OQyLORuuWpAERsA%2BJGyM%2FqSRSmt0vbQ7%2FDvQJG1WdmwzciDhMRH8lJv1Zq4XV089nJFmLhMvUxLxsgd5jzNvIzhXdSs7b4Bpahva6vd2n4y2%2BxaQq1tecOsX3gk7QbNjn%2BGrQbrEVqJbZVlaISNS0hgiK%2BSZVRybKJy5CzQ%2FSX00NKYqY9hycEwqwY8tmRXS%2FHQbOxGRKUSmgyOFniE7J9pdFuVydaLWSeBkQUwZ23DGRbWEB7b%2BtAv0RkJbf3DkcFKK569wrhgZRLp1qFs9enKeq94UA9y4dK1nKEhI8%2BSVFwjoccJokmM7RNpBtFS8g1Bw%2FlQapxUc8wh4Bkp8YEjzQuMRk0Oe6ZadIZe%2BwdKeGZs4YnIgaWfufIANY4VpW3gTtrjQthGJhErTFZQpVbBHYjRYom7aQz39%2B2rfgZ2VP2RnsRyxs5ggx78DOYsROXsgIkwty7qaATf7%2FYDpjyYlhSVEVd0uTW9KihcIY8rlVAJE1dNzJ4NYde59rnpbb2hvxx6nQTvRlMZ30NK3h1q2zu%2BJ6doTarp3UHM5UvOJf7u7jnrPQVWHblatr3nOc5jQaUoPARIj2tPJuVWixfViNBLEu6KHAEYUfR8eplMimfVeOMVttIvNL0sYj2MJaqRqu82bhPZvr2k0q%2B4H%2Ffql2aN4QXgwuaR07W%2FRZ3IA9sIlVVQrvD1wlDrDAKYHgvZSMJXD1WIPsqjvMVpW0nRietbmCsx%2BtqlS%2BgL0oGlwd2GUexbFK1BM8wiEPpkRjYgi%2BKVxid%2BSMxrNGQ%2BJ3pqca3xekbnzUfJdQI8g39y5466tIk%2B%2BoFJfnmMrf%2BQlXHxsphb8m%2Bxe%2FYeiO38UnWSQ465AzvlJMZrDnFKEF0jo7u2gFf%2BHerfn8FcIjt3uslwXhe4fEu%2FxNw%3D%3D%3C%2Fdiagram%3E%3C%2Fmxfile%3E

**Comment by khanshakeeb** [comment]
please upload jpegs on github issue on the following task
https://github.com/khanshakeeb/wad_fall_18_bs/issues/4

I am going to close this taks
